name: Deploy to Pre-Prod

on:
  push:
    branches:
      - pre-prod

jobs:
  deploy:
    name: Deploy to Pre-Prod Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to pre-prod server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          cd /path/to/your/project &&
          git pull origin pre-prod
        "